### ISSUE TITLE
Action fails due to TeXLive

### ISSUE THREAD

**Issue by Yag000** [jonhue/pubtex-action#1]
I'm encountering an issue with this action :
```
" "" "latexmk" "-pdf -file-line-error -halt-on-error -interaction=nonstopmode" "" "" "tlmgr update --self && tlmgr update --all" "" "" "" ""
Run pre compile commands

tlmgr: Local TeX Live (2023) is older than remote repository (2024).
Cross release updates are only supported with
  update-tlmgr-latest(.sh/.exe) --update
See https://tug.org/texlive/upgrade.html for details.
```
and with this configuration file:
```yaml
name: Publish

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Compile and Deploy
        uses: jonhue/pubtex-action@main
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          files: |
            main.tex
```
I've investigated the issue, and it appears to be related to this issue: https://github.com/xu-cheng/latex-action/issues/141\

The problem with the current setup is that the action consistently fails until April 1st.

Based on the discussion in the linked issue, removing l.39 in the file `action.yml` should fix it
```yaml
        pre_compile: tlmgr update --self && tlmgr update --all
```
