### ISSUE TITLE
Compile and Deploy Error

### ISSUE THREAD

**Issue by underscoreHasan** [jonhue/pubtex-action#3]
On the compile and deploy step of the workflow:

`tlmgr: Local TeX Live (2024) is older than remote repository (2025).
Cross release updates are only supported with
  update-tlmgr-latest(.sh/.exe) --update`

publish.yml at https://github.com/underscoreHasan/resume as follows:
```
name: Publish

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Compile and Deploy
        uses: jonhue/pubtex-action@v1.1.0
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          files: |
            resume.tex
```

Log file for this run:
[logs_36280315324.zip](https://github.com/user-attachments/files/19476473/logs_36280315324.zip)

Thank you for the awesome GitHub Action!
